name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build lib
        run: cargo build --verbose -p shady_generator
      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libxcb-shape0-dev libxcb-xfixes0-dev
      - name: build bin
        run: cargo build --verbose -p shady-rs
      - name: build bin with all features
        run: cargo build --all-features --verbose -p shady-rs

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libxcb-shape0-dev libxcb-xfixes0-dev
      - name: test
        run: cargo test --all

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Formatting
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cargo clippy installation
        run: rustup component add clippy
      - name: Cargo clippy check
        run: cargo clippy --all-features --all --tests -- -D warnings

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rustdoc
        run: cargo rustdoc -p shady_generator --all-features